/* Generated By:JavaCC: Do not edit this line. BK_ParserConstants.java */
package edu.soic.Parse.BK;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface BK_ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int OPTION = 7;
  /** RegularExpression Id. */
  int INT = 8;
  /** RegularExpression Id. */
  int ID = 9;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "\"option\"",
    "<INT>",
    "<ID>",
    "\"(\"",
    "\")\"",
    "\"=\"",
    "\".\"",
    "\"predDef:\"",
    "\",\"",
    "\"?\"",
    "\"mode:\"",
    "\"+\"",
    "\"-\"",
    "\"_\"",
    "\"#\"",
  };

}
