/* Generated By:JavaCC: Do not edit this line. Facts_ParserConstants.java */
package edu.soic.Parse.Facts;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface Facts_ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INT = 7;
  /** RegularExpression Id. */
  int ID = 8;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "<INT>",
    "<ID>",
    "\"(\"",
    "\",\"",
    "\").\"",
  };

}
